---
apiVersion: v1
kind: Namespace
metadata:
   name: ashokitns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springbootdeployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: sb-web-app
  template:
    metadata:
      name: springbootwebapppod
      labels:
        app: sb-web-app
     spec:
      containers:
        - name: sbappcontainer
          image: ashokit/sb-logger-app
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: javawebappsvc
  namespace: ashokitns
spec:
  type: LoadBalancer
  selector:
    app: sbapp  #POD label
  ports:
    - port: 80
      targetPort: 8080
...

