---
apiVersion: v1
kind: Namespace
metadata:
  name: spazns
---
apiVersion: apps/v1
kind: Pod
metadata:
  name: sbwebapppod
  labels:
      app: sb-web-app
  namespace: spazns
spec:
  containers:
   - name: sbwebappcontainer
     image: ashokit/sb-logger-app
     ports:
       - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: sbappsvc
  namespace: spazns
spec:
  type: LoadBalancer
  selector:
    app: sb-web-app #POD label
  ports:
    - port: 80
      targetPort: 8080
...
